add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
	
	]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

project_kita/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
import update_status.urls as update_status
import dashboard.urls as dashboard
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^add-friend/', include(add_friend,namespace='add_friend')),
    url(r'^halaman-profile/', include(halaman_profile,namespace='halaman_profile')),
    url(r'^update_status/', include(update_status, namespace='update_status')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
	url(r'^$', RedirectView.as_view(url='/halaman-profile/', permanent="true"), name="index"),
]

update_status/urls.py
from django.conf.urls import url
from .views import index,add_status

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^add_status', add_status, name = 'add_status'),
]

add_friend/models.py
from django.db import models


class Friends(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)

dashboard/models.py
from django.db import models

# Create your models here.

halaman_profile/models.py
from django.db import models

# Create your models here.

update_status/models.py
from django.db import models

class Todo(models.Model):
    status = models.TextField(max_length = 500)
    created_date = models.DateTimeField(auto_now_add = True)

# Create your models here.

add_friend/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'type' : 'text',
        'class': 'form-control',
        'placeholder': 'Masukan Nama...'
    }
    url = {
        'type' : 'url',
        'class': 'form-control',
        'placeholder': 'Masukan URL...'
    }

    name = forms.CharField(label='Name', required=True,
                           max_length=27,
                           widget=forms.TextInput(attrs=attrs)
                           )

    url = forms.URLField(label="URL", required=True,
                             widget=forms.TextInput(attrs=url)
                             )

update_status/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    status_attrs = {
        'type': 'text',
        'cols': 176,
        'rows': 5,
        'class': 'todo-form-textarea',
        'placeholder':'whats going on?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from urllib.request import urlopen
from urllib.error import URLError
from .forms import Message_Form
from .models import Friends


# Create your views here.
landing_page_content = "Usamah nashirulhaq"
response = {'author': "Usamah nashirulhaq"}
def index(request):
    message = Friends.objects.all()
    response['message_form'] = Message_Form
    response['message'] = message
    html = 'add_friend/add_friend.html'
    return render(request,html,response)

def add_friend(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] 
        response['url'] = request.POST['url'] 
        message = Friends(name=response['name'], url=response['url'])
        message.save()
        html ='add_friend/form_result.html'
        # return render(request, html, response)
        return HttpResponseRedirect('/add-friend/')
    else:
        return HttpResponseRedirect('/add-friend/')

def url_is_valid(url):
    try:
        thepage = urlopen(url)
    except URLError as e:
        return False
    else:
        return True

dashboard/views.py
from django.shortcuts import render
from add_friend.models import Friends
from update_status.models import Todo
from halaman_profile.views import profile_name
#from blabla import bla

# Create your views here.
response = {}
def index(request):
	response['friends'] = Friends.objects.all().count();
	response['post'] = Todo.objects.all().count();
	#todo = Todo.objects.all()
	#response['data'] = sesuatu.objects.all()
	response['name'] = profile_name
	
	response['status'] = Todo.objects.last()
	html = 'dashboard/dashboard.html'
	return render(request, html, response)

halaman_profile/views.py
from django.shortcuts import render

profile_name = 'Hepzibah Smith'
bio_dict = [{'subject' : 'Birthday', 'value' : '01 Jan'},\
{'subject' : 'Gender', 'value' : 'Female'},\
{'subject' : 'Expertise', 'value' : 'Marketing, Collector, Public Speaking'},\
{'subject' : 'Description', 'value' : 'Antique expert. Experience as marketer for 10 years'},\
{'subject' : 'Email', 'value' : 'hello@smith.com'}]
expertise = {'Marketing', 'Collector', 'Public Speaking'}

# Create your views here.
def index(request):
    response = {'bio_dict': bio_dict, 'profile_name': profile_name}
    return render(request, 'desc_halamanprofile.html', response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from halaman_profile.views import profile_name
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):
    todo = Todo.objects.order_by('-id')
    response['todo'] = todo
    html = 'update_status/index.html'
    response['namaku'] = profile_name
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_status(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        todo = Todo(status=response['status'])
        todo.save()
        return HttpResponseRedirect('/update_status/')
    else:
        return HttpResponseRedirect('/update_status/')

add_friend/templates/add_friend/add_friend.html
{% extends "add_friend/layout/base.html" %}

    {% block content %}
<div class="seluruh-page">
    <div class="bagian-kiri" style="float:left">
	<section name="form", id="input-list">
        <div class="containerd">
        <form id="form" method="POST" action="{% url 'add_friend:add_friend'%}">
            <h2>add new friends here!</h2>
            {% csrf_token %}
            {{ message_form }}
            <br>
            <button id="submit" type="submit" class="btn btn-lg btn-block btn-info" style="background: aqua">Add</button>
            <br>
        </form>
        </div>
    </section>
    </div>
    <div class="bagian-kanan" style="float : right">
    <section name="my-list" id="my-list">
    
        <h2 class="my-list-title">my friend</h2>
        <div class="flex">
                {% for data in message %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-title">
                                {{data.name}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="to-do-list-description"><a href="{{data.url}}">
                                {{data.url}}</a>
                            </div><!-- 
                            <div class="to-do-list-delete">
                                <div class="to-do-list-delete-button">Delete</div></a>
                            </div> -->
                        </div>
                    </div>
                {% endfor %}
        </div>
    
    </section>
</div>
</div>
    {% endblock %}

add_friend/templates/add_friend/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <title> 
        profile
    </title>
</head>

<body>
    <header>
        <!-- templates/lab_5/partials/header.html -->
        <nav class="navbar navbar-default">
          <div class="container">  
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!-- <a class="navbar-brand" href="">Lingin</a> -->
            </div>
        </div>
            <div id="navbar" class="navbar-collapse collapse">
                <div class="navbar-brand"><a href="{% url 'update_status:index' %}">Lingin</a></div>
              <ul>
                <!-- LINK MENUJU table, dan link menuju home#form -->
                <!-- <li class="navbar-brand"><a href="">Lingin</a></li> -->
                <li><a href="{% url 'update_status:index' %}">Status</a> </li>
                <li><a href="{% url 'halaman_profile:index' %}">Profile</a></li>
                <li class="active"><a href="{% url 'add_friend:index' %}">Friends</a> </li>
                <li><a href="{% url 'dashboard:index' %}">Dashboard</a> </li>
              </ul>
            </div><!--/.nav-collapse -->
        </nav>
    </header>

    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>
    </content>

    <footer class="footer">
        <div>&copy; Made by Project Kita</div>
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

add_friend/templates/add_friend/partials/footer.html
<div>
	
		<h4 style="text-align: center;">&copy; KELOMPOK PPW</h4>
	
<div>

add_friend/templates/add_friend/partials/header.html
<style>
.container{
	height: 260px;
}

.jumbotron{
	background-color: #214493;
}

.navbar-default .navbar-nav > li { padding: 0px 0px 0px 10px; }
.navbar-default .navbar-nav > li > a {font-family: Comic Sans MS; transition: 0.4s;}
.navbar-default .navbar-nav > .active > a{background-color: #CD2D31; color: white;}

.navbar-default .navbar-nav > li > a:hover { background-color: #CD2D31 !important; color: white !important;}

</style>
<div class="container">
  <div class="jumbotron" style="background-color: #214493;">
    <h1 style="color: white; font-family: Comic Sans MS; font-size: 60px; margin:0px 0px 0px 0px;">Ling In</h1>
	<nav class="navbar navbar-default" style="margin:30px 0px 0px 0px; border-color: #2C2C2C; border-radius: 0%; box-shadow: 10px 10px 10px black;">
    <div class="container-fluid">
      <ul class="nav navbar-nav navbar-right" style="font-size: 20px;">
        {% if request.get_full_path == "/" %} <li class="active"><a href="#"><b>Status</b></a></li> 
			{% else %} <li><a href="#"><b>Home</b></a></li> {% endif %}
		{% if request.get_full_path == "/account/login/" %} <li class="active"><a href="#"><b>Profile</b></a></li> 
			{% else %} <li><a href="#"><b>Profile</b></a></li> {% endif %}
		{% if request.get_full_path == "/account/login/" %} <li class="active"><a href="/add-friend/"><b>Friends</b></a></li> 
			{% else %} <li><a href="#"><b>Friends</b></a></li> {% endif %}
		{% if request.get_full_path == "/dashboard/" %} <li class="active"><a href="#"><b>Stats</b></a></li>
			{% else %} <li><a href="#"><b>Stats</b></a></li> {% endif %}
      </ul>
    </div>
  </nav>
  </div>
  
</div>

dashboard/templates/dashboard/dashboard.html
{% extends "dashboard/layout/base.html" %}
{% block content %}
{% load static%}

<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}" />  
<h2 class="judul">Statistic</h2>
<div id="terluar">
	<h2 class="nama_dashboard"><img src="https://i.pinimg.com/564x/c3/36/7f/c3367fd7df9d650ef5648fb8e3233cf7.jpg" height="230" width="230"></img>{{name}}</h2>
	<div>
		<p class="blokB">Friends :  {{friends}} People</p>
		<p class="blokB">Feed :  {{post}} Post</p>
	</div>
	<br>
	<h2 class="judul" style="font-size: 30px; color: white;">Latest Post</h2>
		<br>
		<div class="panel">
			<h4 class="nama_status"><img style="border-radius: 50%; margin: 0px 30px 0px 0px; "src="https://i.pinimg.com/564x/c3/36/7f/c3367fd7df9d650ef5648fb8e3233cf7.jpg" height="70" width="70"></img>{{name}}</h4>
			<hr size="100px" color="red">
			<h4><b>{{status.status}}</b><h4>
			<p style="color: grey">{{status.created_date}}</p>
		</div>
</div>

{% endblock %}

dashboard/templates/dashboard/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <title> 
       Dashboard
    </title>
</head>

<body>
    <header>
        <!-- templates/lab_5/partials/header.html -->
        <nav class="navbar navbar-default">
          <div class="container">  
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
        </div>
            <div id="navbar" class="navbar-collapse collapse">
                <div class="navbar-brand"><a href="{% url 'update_status:index' %}">Lingin</a></div>
              <ul>
                <li><a href="{% url 'update_status:index' %}">Status</a> </li>
                <li><a href="{% url 'halaman_profile:index' %}">Profile</a></li>
                <li><a href="{% url 'add_friend:index' %}">Friends</a> </li>
                <li class="active"><a href="{% url 'dashboard:index' %}">Dashboard</a> </li>
              </ul>
            </div><!--/.nav-collapse -->
        </nav>
    </header>

    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>

    <footer class="footer">
        <div>&copy; Made by Project Kita</div>
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

halaman_profile/templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <title> 
        profile
    </title>
</head>

<body>
    <header>
        <!-- templates/lab_5/partials/header.html -->
        <nav class="navbar navbar-default">
          <div class="container">  
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              
            </div>
        </div>
            <div id="navbar" class="navbar-collapse collapse">
                <div class="navbar-brand"><a href="{% url 'update_status:index' %}">Lingin</a></div>
              <ul>
                <!-- LINK MENUJU table, dan link menuju home#form -->
                <li><a href="{% url 'update_status:index' %}">Status</a> </li>
                <li class="active"><a href="{% url 'halaman_profile:index' %}">Profile</a></li>
                <li><a href="{% url 'add_friend:index' %}">Friends</a> </li>
                <li><a href="{% url 'dashboard:index' %}">Dashboard</a> </li>
              </ul>
            </div><!--/.nav-collapse -->
          
          </div>
        </nav>
    </header>

    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>

    <footer class="footer">
        <div>&copy; Made by Project Kita</div>
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

halaman_profile/templates/desc_halamanprofile.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/halaman_profile.css' %}" />  
<body>
<div class="halaman-profile">
    <div class="title">
        <h5>PROFILE</h5>
        <div class="profile-picture">
            <img src="https://i.pinimg.com/564x/c3/36/7f/c3367fd7df9d650ef5648fb8e3233cf7.jpg" alt="my-image">
            <h1 class="nama">{{profile_name}}</h1>
        </div>
    </div> 
<!-- profile & foto -->

    <div class ="profile-info">
        <table class="profile-table">
            {% for bio in bio_dict %}
                <tr>
                    <td class="subject"> <strong>{{ bio.subject }}</strong></td>
                    <td class="value"> {{ bio.value }} </td>
                </tr>
            {% endfor %}
        </table>
    </div>     
</div>
</body>

{% endblock %}

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Project Kita">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
    <title> 
        Project Kita
    </title>
</head>

<body>
    <header>
       {% include "partials/header.html"%}
    </header>
    <content>
      <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
      </div>
    </content>

    <footer class="footer">
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

update_status/templates/update_status/index.html
{% extends "update_status/layout/base.html" %}
{% block content %}


<form method="POST" action="{% url 'update_status:add_status' %}">
    <div style="width: 100%;background: white;
  border-radius: 3px;
  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
  padding: 20px 30px;
  position: relative;">
        <!-- <div class="form"> -->
            <h2>What's New?</h2>
            {% csrf_token %}
            {{ todo_form }}
          
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>  
        </div>
        <!-- </div> -->
</form>

<div class="container-status">
    {% for data in todo %}
    <div class="status-item">
        <div class="namaku">{{namaku}}
        <div class="status-list-date">{{data.created_date}}</div></div>
                        <div class="status-list">
                            <div class="status-list-status">
                                {{data.status}}
                            </div>
                        </div>
                    </div>
     {% endfor %}
 </div>
   


{% endblock %}

update_status/templates/update_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <title> 
		Status
    </title>
</head>

<body>
    <header>
        <!-- templates/lab_5/partials/header.html -->
        <nav class="navbar navbar-default">
          <div class="container">  
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
        </div>
            <div id="navbar" class="navbar-collapse collapse">
                <div class="navbar-brand"><a href="{% url 'update_status:index' %}">Lingin</a></div>
              <ul>
                <li class="active"><a href="{% url 'update_status:index' %}">Status</a> </li>
                <li><a href="{% url 'halaman_profile:index' %}">Profile</a></li>
                <li><a href="{% url 'add_friend:index' %}">Friends</a> </li>
                <li><a href="{% url 'dashboard:index' %}">Dashboard</a> </li>
              </ul>
            </div><!--/.nav-collapse -->
        </nav>
    </header>

    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>

    <footer class="footer">
        <div>&copy; Made by Project Kita</div>
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>